[build]
  publish = "."
  functions = "netlify/functions"

# Admin: doprowadź /admin do katalogu
[[redirects]]
  from = "/admin"
  to   = "/admin/"
  status = 301

# Bardzo ważne – NIE przepisywać config.yml
[[redirects]]
  from = "/admin/config.yml"
  to   = "/admin/config.yml"
  status = 200

# Serwuj panel Decap (index.html) dla pozostałych ścieżek w /admin/*
[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200

# (Jeśli masz SPA catch-all, zostaw go NA KOŃCU)
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200
