[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/"
  status = 200
  force = true
  conditions = { Role = ["staff", "editor", "admin"] }

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 302
  force = true
