[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/admin/*"
  to = "/admin/"
  status = 200
  force = true
  conditions = { Role = ["staff", "editor", "admin"] }

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 302
  force = true
